export const colors = {
  white: '#F5F5F5',
  blue: '#0892D0',
  blueNew:'#066692',
  charcoal: '#263539',
  black: '#000000',
  black30: 'rgba(0,0,0,0.3)',
  black50: 'rgba(0,0,0,0.5)',
  placeholder: '#263539',
  lightColor: 'rgba(38, 53, 57, 0.8)',
  borderColor: '#B7BBBC',
  black100: '#171717',
  red: '#FF0000',
  black: {
    100: '#171717',
  },

  grey: {
    100: '#E3E3E3',
    200: '#EAEAEA',
  },
  white100: 'F8F5F5',
};

export const fonts = {
  abhayaBold: 'AbhayaLibre-Bold',
  abhayaExtraBold: 'AbhayaLibre-ExtraBold',
  abhayaMedium: 'AbhayaLibre-Medium',
  abhayaRegular: 'AbhayaLibre-Regular',
  abhayaSemiBold: 'AbhayaLibre-SemiBold',
  poppinsBlack: 'Poppins-Black',
  poppinsBlackItalic: 'Poppins-BlackItalic',
  poppinsBold: 'Poppins-Bold',
  poppinsBoldItalic: 'Poppins-BoldItalic',
  poppinsExtraBold: 'Poppins-ExtraBold',
  poppinsExtraBoldItalic: 'Poppins-ExtraBoldItalic',
  poppinsExtraLight: 'Poppins-ExtraLight',
  poppinsExtraLightItalic: 'Poppins-ExtraLightItalic',
  poppinsLight: 'Poppins-Light',
  poppinsItalic: 'Poppins-Italic',
  poppinsLightItalic: 'Poppins-LightItalic',
  poppinsMedium: 'Poppins-Medium',
  poppinsMediumItalic: 'Poppins-MediumItalic',
  poppinsRegular: 'Poppins-Regular',
  poppinsSemiBold: 'Poppins-SemiBold',
  poppinsSemiBoldItalic: 'Poppins-SemiBoldItalic',
  poppinsThin: 'Poppins-Thin',
  poppinsThinItalic: 'Poppins-ThinItalic',
};
