export const STRINGS = {
  WHERE_LIVE: 'Where do you live?',
  WHICH_GENDER: 'Which gender best describes you?',
  JOB_EXPRIENCE: 'What’s your job experience?',
  COMPANY_NAME: 'Company Name',
  INDUSTRY: 'Industry',
  DESIGNATION: 'Designation',
  CURRENTLY_WORKING: 'Currently working',
  START_DATE: 'Start Date',
  CURRENTLY_PURSUING: 'Currently Pursuing',
  END_DATE: 'End Date',
  VIRTUALLY_WORKING: 'Virtually Working',
  WORK_HOME: 'Work from home',
  HYBRID_MODE: 'Hybrif mode',
  EDUCATION: 'Education',
  DEGREE: 'Degree',
  SCHOOL: 'School',
  FIELD_STUDY: 'Field of study',
  PURSURING: 'Pursuring',
  PLACE: 'Place',
  DESCRIPTION: 'Description',
  EDIT: 'Edit',
  LOOKINGFOR: 'Looking For',
  YOURCORESKILLS: 'Your Core Skills',
  REQUIRECORESKILLS: 'Require Core Skills',
  AREOFINTREST: 'Area of Interest',
  IDEA: 'Idea',
  PROBLEMSTATEMENT: 'Problem Statement',
  PERSONALDETAILS: 'Personal Details',
  SKILSS: 'Skills',
  EXPRIENCE: 'Exprience',
  FIRSTNAME: 'First name',
  LASTNAME: 'Last name',
  DOB: 'Date of birth',
  GENDER: 'Gender',
  PHONENO: '+91 ',
  EMAIL: 'Email Address',
  LCOATION: 'Location',
  SAVE: 'Save',
  WORKEDUCATION: 'Work & Education',
  WORK: 'Work',
  EDUCATION: 'Education',
  INDUSTRY: 'Industry of work',
  ADDMORE: 'Add More',
  DELETE: 'Remove',
  UNIVERSITY: 'University Name',
  SELECTGENDER: 'Select your gender',
  CAMERA: 'Camera',
  GALLERY: 'Gallery',
  MALE: 'Male',
  FEMALE: 'Female',
  NONBINARY: 'Non-Binary',
  PREFERNOT: 'Prefer not to answer',
  CONNECT: 'Connect',
  CONNECT_CONTENT: 'Link a shared passion and innovation through connection.',
  COMMUNICATE: 'Communicate',
  COMMUNICATE_CONTENT:
    'Building bridges of communication for co-founders to thrive',
  COLLABORATE: 'Collaborate',
  COLLABORATE_CONTENT: 'Drive innovation through collaborative partnerships.',
  SEARCH_SKILLS: 'Search for skills',
  SEARCH_SKILLS_BELOWLINE: 'Pick things you’d like to see on your profile',
  RESUME_HEADING: 'Upload Resume (Optional)',
  ATTACHMENT_TEXT: 'Add attachment',
  ATTACHMENT_TEXT2: 'Select attachment to upload',
  PHOTOS_VIDEOS_HEADING: 'Add Photos & Videos',
  PHOTOS_REQUIRED_TEXT: '4 photos/videos required',
  PROMPTS_HEADING: 'Write a Prompts(2)',
  PROMPTS_TEXT1: 'Select a Prompt',
  PROMPTS_TEXT2: 'and write your own answer',
  LOOKING_FOR: 'You are looking for?',
  CORE_SKILLS: 'Your Expertise',
  EXPECTED_SKILLS: 'Skills your are expecting?',
  AREA_INTEREST: 'Area of Interest?',
  BUSINESS_IDEA: 'Do you have any business idea?',
  EXPECTED_EXPERTISE: 'Expected Expertise'
};
